### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by lm913** [abhisheksoni27/codespell#5]
Hello! I'm now receiving the following error in regards to reading and writing:
`EACCES: permission denied, open '/Users/********/.codespell/codespell-Mon-Jul-24-2017.json'`

I've tried with and without `sudo` and my folder permissions are Read/Write

<img width="907" alt="screen shot 2017-07-24 at 9 35 55 am" src="https://user-images.githubusercontent.com/6440325/28525912-d171c6a8-7053-11e7-9158-7fd22c1d6abe.png">

**Comment by abhisheksoni27** [comment]
Just to be sure: Can you run `chmod -R 777 $HOME/.codespell` and try again?

**Comment by lm913** [comment]
Did that, now receiving:

```
{ Error: Command failed: resize
/bin/sh: resize: command not found

    at ChildProcess.exithandler (child_process.js:270:12)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at maybeClose (internal/child_process.js:921:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5) killed: false, code: 127, signal: null, cmd: 'resize' }
```

**Comment by abhisheksoni27** [comment]
Interesting. `resize` command is not there in OSX. 

Changed the command to `tput cols`, should fix it.
